### ISSUE TITLE
Determine 10-20 AOIs for determining necessary spectra

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#71]
In terms of #70 there is a need input AOIs and AVIRIS scenes. 

This task is to extract from the [GeoPackage](https://github.com/azavea/nasa-hyperspectral/issues/52#issuecomment-737428389) we have AOIs that potentially can be interesting for the further research.

The result AOIs would be used in the future to schedule AVIRIS scenes download and preprocessing https://github.com/azavea/nasa-hyperspectral/issues/55.

**Comment by jpolchlo** [comment]
In order to get down to a final list of AOIs, I could use COGified versions of the scene IDs listed below.  There are _a lot_ (546) such scenes.  I can surely reduce the number if that's useful.  Probably get it to substantially under 200.  LMK if that's a benefit.

As a side note, a Franklin query for these IDs returned a feature collection with the context line `{'returned': 30, 'matched': 3741}`, which if I'm reading right means there were almost 7 times as many hits returned as scene ids requested?  Wonder if there's any clarification to be found on this point.

aviris_f130410t01p00r10_sc01
aviris_f130410t01p00r11_sc01
aviris_f130410t01p00r12_sc01
aviris_f130410t01p00r13_sc01
aviris_f130410t01p00r14_sc01
aviris_f130410t01p00r15_sc01
aviris_f130410t01p00r16_sc01
aviris_f130410t01p00r17_sc01
aviris_f130410t01p00r18_sc01
aviris_f130410t01p00r19_sc01
aviris_f130411t01p00r07_sc01
aviris_f130411t01p00r13_sc01
aviris_f130411t01p00r15_sc01
aviris_f130411t01p00r17_sc01
aviris_f130412t01p00r06_sc01
aviris_f130412t01p00r07_sc01
aviris_f130412t01p00r08_sc01
aviris_f130412t01p00r09_sc01
aviris_f130412t01p00r10_sc01
aviris_f130412t01p00r11_sc01
aviris_f130412t01p00r13_sc01
aviris_f130412t01p00r14_sc01
aviris_f130419t01p00r07_sc01
aviris_f130419t01p00r08_sc01
aviris_f130419t01p00r09_sc01
aviris_f130419t01p00r10_sc01
aviris_f130419t01p00r11_sc01
aviris_f130419t01p00r12_sc01
aviris_f130419t01p00r13_sc01
aviris_f130419t01p00r14_sc01
aviris_f130419t01p00r15_sc01
aviris_f130502t01p00r07_sc01
aviris_f130502t01p00r13_sc01
aviris_f130502t01p00r14_sc01
aviris_f130502t01p00r15_sc01
aviris_f130502t01p00r18_sc01
aviris_f130502t01p00r20_sc01
aviris_f130502t01p00r23_sc01
aviris_f130503t01p00r14_sc01
aviris_f130503t01p00r15_sc01
aviris_f130503t01p00r18_sc01
aviris_f130503t01p00r19_sc01
aviris_f130503t01p00r22_sc01
aviris_f130522t01p00r06_sc01
aviris_f130522t01p00r07_sc01
aviris_f130522t01p00r08_sc01
aviris_f130522t01p00r09_sc01
aviris_f130522t01p00r10_sc01
aviris_f130522t01p00r11_sc01
aviris_f130522t01p00r12_sc01
aviris_f130522t01p00r13_sc01
aviris_f130522t01p00r14_sc01
aviris_f130522t01p00r15_sc01
aviris_f130604t01p00r08_sc01
aviris_f130604t01p00r11_sc01
aviris_f130604t01p00r13_sc01
aviris_f130606t01p00r05_sc01
aviris_f130606t01p00r10_sc01
aviris_f130606t01p00r11_sc01
aviris_f130606t01p00r13_sc01
aviris_f130606t01p00r18_sc01
aviris_f130607t01p00r05_sc01
aviris_f130607t01p00r06_sc01
aviris_f130607t01p00r07_sc01
aviris_f130607t01p00r08_sc01
aviris_f130607t01p00r09_sc01
aviris_f130607t01p00r10_sc01
aviris_f130607t01p00r11_sc01
aviris_f130607t01p00r12_sc01
aviris_f130607t01p00r13_sc01
aviris_f130607t01p00r14_sc01
aviris_f130612t01p00r06_sc01
aviris_f130612t01p00r07_sc01
aviris_f130612t01p00r10_sc01
aviris_f130612t01p00r11_sc01
aviris_f130612t01p00r14_sc01
aviris_f130612t01p00r16_sc01
aviris_f130626t01p00r06_sc01
aviris_f130626t01p00r07_sc01
aviris_f130821t01p00r05_sc01
aviris_f130821t01p00r09_sc01
aviris_f130913t01p00r05_sc01
aviris_f130924t01p00r06_sc01
aviris_f130924t01p00r07_sc01
aviris_f130924t01p00r08_sc01
aviris_f130924t01p00r09_sc01
aviris_f130924t01p00r10_sc01
aviris_f130924t01p00r11_sc01
aviris_f130924t01p00r12_sc01
aviris_f130924t01p00r13_sc01
aviris_f131117t01p00r05_sc01
aviris_f131117t01p00r06_sc01
aviris_f131117t01p00r07_sc01
aviris_f131117t01p00r08_sc01
aviris_f131117t01p00r09_sc01
aviris_f131125t01p00r05_sc01
aviris_f131125t01p00r07_sc01
aviris_f131125t01p00r13_sc01
aviris_f131125t01p00r14_sc01
aviris_f131125t01p00r15_sc01
aviris_f140331t01p00r12_sc01
aviris_f140331t01p00r13_sc01
aviris_f140407t01p00r06_sc01
aviris_f140407t01p00r07_sc01
aviris_f140407t01p00r10_sc01
aviris_f140407t01p00r11_sc01
aviris_f140407t01p00r12_sc01
aviris_f140407t01p00r16_sc01
aviris_f140407t01p00r18_sc01
aviris_f140410t01p00r10_sc01
aviris_f140410t01p00r13_sc01
aviris_f140410t01p00r15_sc01
aviris_f140410t01p00r18_sc01
aviris_f140414t01p00r06_sc01
aviris_f140414t01p00r07_sc01
aviris_f140414t01p00r08_sc01
aviris_f140414t01p00r09_sc01
aviris_f140414t01p00r10_sc01
aviris_f140414t01p00r11_sc01
aviris_f140414t01p00r12_sc01
aviris_f140414t01p00r13_sc01
aviris_f140414t01p00r14_sc01
aviris_f140414t01p00r15_sc01
aviris_f140416t01p00r07_sc01
aviris_f140416t01p00r08_sc01
aviris_f140416t01p00r09_sc01
aviris_f140416t01p00r13_sc01
aviris_f140416t01p00r15_sc01
aviris_f140418t01p00r06_sc01
aviris_f140418t01p00r07_sc01
aviris_f140418t01p00r09_sc01
aviris_f140418t01p00r10_sc01
aviris_f140418t01p00r11_sc01
aviris_f140419t01p00r05_sc01
aviris_f140419t01p00r06_sc01
aviris_f140419t01p00r07_sc01
aviris_f140419t01p00r08_sc01
aviris_f140423t01p00r06_sc01
aviris_f140423t01p00r07_sc01
aviris_f140423t01p00r08_sc01
aviris_f140423t01p00r10_sc01
aviris_f140507t01p00r05_sc01
aviris_f140507t01p00r06_sc01
aviris_f140507t01p00r07_sc01
aviris_f140507t01p00r08_sc01
aviris_f140507t01p00r10_sc01
aviris_f140507t01p00r11_sc01
aviris_f140507t01p00r12_sc01
aviris_f140507t01p00r13_sc01
aviris_f140507t01p00r15_sc01
aviris_f140507t01p00r16_sc01
aviris_f140528t01p00r06_sc01
aviris_f140528t01p00r07_sc01
aviris_f140528t01p00r08_sc01
aviris_f140528t01p00r09_sc01
aviris_f140528t01p00r10_sc01
aviris_f140528t01p00r11_sc01
aviris_f140528t01p00r12_sc01
aviris_f140528t01p00r13_sc01
aviris_f140528t01p00r14_sc01
aviris_f140528t01p00r15_sc01
aviris_f140528t01p00r16_sc01
aviris_f140602t01p00r12_sc01
aviris_f140602t01p00r15_sc01
aviris_f140602t01p00r17_sc01
aviris_f140603t01p00r09_sc01
aviris_f140603t01p00r10_sc01
aviris_f140603t01p00r15_sc01
aviris_f140603t01p00r18_sc01
aviris_f140603t01p00r20_sc01
aviris_f140603t01p00r21_sc01
aviris_f140604t01p00r06_sc01
aviris_f140606t02p00r04_sc01
aviris_f140606t02p00r05_sc01
aviris_f140606t02p00r06_sc01
aviris_f140606t02p00r07_sc01
aviris_f140606t02p00r10_sc01
aviris_f140613t01p00r05_sc01
aviris_f140613t01p00r06_sc01
aviris_f140613t01p00r07_sc01
aviris_f140613t01p00r09_sc01
aviris_f140613t01p00r10_sc01
aviris_f140613t01p00r11_sc01
aviris_f140613t01p00r12_sc01
aviris_f140613t01p00r13_sc01
aviris_f140818t01p00r09_sc01
aviris_f140818t01p00r10_sc01
aviris_f140818t01p00r11_sc01
aviris_f140818t01p00r12_sc01
aviris_f140818t01p00r13_sc01
aviris_f140818t01p00r14_sc01
aviris_f140826t01p00r05_sc01
aviris_f140826t01p00r06_sc01
aviris_f140826t01p00r07_sc01
aviris_f140826t01p00r08_sc01
aviris_f140826t01p00r09_sc01
aviris_f140826t01p00r10_sc01
aviris_f140826t01p00r11_sc01
aviris_f140826t01p00r12_sc01
aviris_f140826t01p00r13_sc01
aviris_f140829t01p00r06_sc01
aviris_f140829t01p00r08_sc01
aviris_f140829t01p00r12_sc01
aviris_f140829t01p00r14_sc01
aviris_f140919t01p00r11_sc01
aviris_f140919t01p00r14_sc01
aviris_f140919t01p00r16_sc01
aviris_f140919t01p00r20_sc01
aviris_f141006t01p00r06_sc01
aviris_f141006t01p00r07_sc01
aviris_f141006t01p00r10_sc01
aviris_f141006t01p00r11_sc01
aviris_f141006t01p00r14_sc01
aviris_f141006t01p00r16_sc01
aviris_f141021t01p00r05_sc01
aviris_f141027t01p00r05_sc01
aviris_f141027t01p00r06_sc01
aviris_f141027t01p00r07_sc01
aviris_f141027t01p00r08_sc01
aviris_f141027t01p00r09_sc01
aviris_f141027t01p00r10_sc01
aviris_f141027t01p00r11_sc01
aviris_f141027t01p00r12_sc01
aviris_f141027t01p00r13_sc01
aviris_f141027t01p00r14_sc01
aviris_f141027t01p00r15_sc01
aviris_f141117t01p00r11_sc01
aviris_f141117t01p00r14_sc01
aviris_f141117t01p00r16_sc01
aviris_f141124t01p00r07_sc01
aviris_f141124t01p00r08_sc01
aviris_f141124t01p00r09_sc01
aviris_f141124t01p00r10_sc01
aviris_f141124t01p00r11_sc01
aviris_f141124t01p00r13_sc01
aviris_f141124t01p00r14_sc01
aviris_f150120t01p00r07_sc01
aviris_f150120t01p00r09_sc01
aviris_f150120t01p00r10_sc01
aviris_f150120t01p00r12_sc01
aviris_f150120t01p00r13_sc01
aviris_f150120t01p00r14_sc01
aviris_f150120t01p00r15_sc01
aviris_f150127t01p00r07_sc01
aviris_f150127t01p00r08_sc01
aviris_f150127t01p00r09_sc01
aviris_f150127t01p00r12_sc01
aviris_f150127t01p00r13_sc01
aviris_f150127t01p00r16_sc01
aviris_f150205t01p00r06_sc01
aviris_f150206t01p00r06_sc01
aviris_f150206t01p00r11_sc01
aviris_f150206t01p00r12_sc01
aviris_f150210t01p00r05_sc01
aviris_f150210t01p00r06_sc01
aviris_f150210t01p00r07_sc01
aviris_f150210t01p00r10_sc01
aviris_f150210t01p00r11_sc01
aviris_f150220t01p00r06_sc01
aviris_f150224t01p00r05_sc01
aviris_f150224t01p00r09_sc01
aviris_f150416t01p00r05_sc01
aviris_f150416t01p00r06_sc01
aviris_f150416t01p00r08_sc01
aviris_f150416t01p00r10_sc01
aviris_f150416t01p00r15_sc01
aviris_f150416t01p00r16_sc01
aviris_f150428t01p00r05_sc01
aviris_f150428t01p00r06_sc01
aviris_f150428t01p00r07_sc01
aviris_f150428t01p00r08_sc01
aviris_f150428t01p00r09_sc01
aviris_f150428t01p00r10_sc01
aviris_f150428t01p00r11_sc01
aviris_f150428t01p00r12_sc01
aviris_f150428t01p00r13_sc01
aviris_f150428t01p00r14_sc01
aviris_f150428t01p00r15_sc01
aviris_f150429t01p00r09_sc01
aviris_f150429t01p00r11_sc01
aviris_f150429t01p00r13_sc01
aviris_f150429t01p00r18_sc01
aviris_f150430t01p00r06_sc01
aviris_f150430t01p00r07_sc01
aviris_f150430t01p00r08_sc01
aviris_f150430t01p00r09_sc01
aviris_f150430t01p00r10_sc01
aviris_f150430t01p00r11_sc01
aviris_f150430t01p00r12_sc01
aviris_f150430t01p00r13_sc01
aviris_f150430t01p00r14_sc01
aviris_f150430t01p00r15_sc01
aviris_f150430t01p00r16_sc01
aviris_f150505t01p00r08_sc01
aviris_f150505t01p00r09_sc01
aviris_f150505t01p00r12_sc01
aviris_f150505t01p00r13_sc01
aviris_f150505t01p00r16_sc01
aviris_f150505t01p00r18_sc01
aviris_f150505t01p00r19_sc01
aviris_f150505t01p00r20_sc01
aviris_f150528t01p00r06_sc01
aviris_f150528t01p00r07_sc01
aviris_f150528t01p00r08_sc01
aviris_f150528t01p00r09_sc01
aviris_f150528t01p00r10_sc01
aviris_f150528t01p00r11_sc01
aviris_f150528t01p00r12_sc01
aviris_f150528t01p00r13_sc01
aviris_f150528t01p00r14_sc01
aviris_f150601t01p00r06_sc01
aviris_f150601t01p00r07_sc01
aviris_f150601t01p00r10_sc01
aviris_f150601t01p00r11_sc01
aviris_f150601t01p00r14_sc01
aviris_f150602t01p00r06_sc01
aviris_f150602t01p00r11_sc01
aviris_f150602t01p00r12_sc01
aviris_f150602t01p00r14_sc01
aviris_f150602t01p00r16_sc01
aviris_f150602t01p00r21_sc01
aviris_f150611t01p00r10_sc01
aviris_f150611t01p00r11_sc01
aviris_f150611t01p00r12_sc01
aviris_f150611t01p00r13_sc01
aviris_f150611t01p00r14_sc01
aviris_f150611t01p00r15_sc01
aviris_f150611t01p00r16_sc01
aviris_f150611t01p00r17_sc01
aviris_f150611t01p00r18_sc01
aviris_f150611t01p00r19_sc01
aviris_f150611t01p00r20_sc01
aviris_f150615t01p00r05_sc01
aviris_f150615t01p00r06_sc01
aviris_f150615t01p00r07_sc01
aviris_f150615t01p00r08_sc01
aviris_f150615t01p00r10_sc01
aviris_f150615t01p00r11_sc01
aviris_f150615t01p00r12_sc01
aviris_f150615t01p00r15_sc01
aviris_f150615t01p00r16_sc01
aviris_f150615t01p00r17_sc01
aviris_f150824t01p00r07_sc01
aviris_f150824t01p00r08_sc01
aviris_f150824t01p00r11_sc01
aviris_f150824t01p00r15_sc01
aviris_f151002t01p00r06_sc01
aviris_f151002t01p00r07_sc01
aviris_f151002t01p00r08_sc01
aviris_f151002t01p00r09_sc01
aviris_f151002t01p00r10_sc01
aviris_f151002t01p00r11_sc01
aviris_f151002t01p00r12_sc01
aviris_f151002t01p00r13_sc01
aviris_f151002t01p00r16_sc01
aviris_f151002t01p00r17_sc01
aviris_f151002t01p00r18_sc01
aviris_f151002t01p00r19_sc01
aviris_f151013t01p00r10_sc01
aviris_f151013t01p00r11_sc01
aviris_f151013t01p00r15_sc01
aviris_f151020t01p00r06_sc01
aviris_f151020t01p00r08_sc01
aviris_f151020t01p00r12_sc01
aviris_f151020t01p00r13_sc01
aviris_f151020t01p00r14_sc01
aviris_f151020t01p00r17_sc01
aviris_f151021t01p00r05_sc01
aviris_f151021t01p00r06_sc01
aviris_f151021t01p00r07_sc01
aviris_f151021t01p00r08_sc01
aviris_f151021t01p00r09_sc01
aviris_f151021t01p00r10_sc01
aviris_f151021t01p00r11_sc01
aviris_f151021t01p00r12_sc01
aviris_f151021t01p00r13_sc01
aviris_f151022t01p00r05_sc01
aviris_f151022t01p00r06_sc01
aviris_f151022t01p00r07_sc01
aviris_f151026t01p00r06_sc01
aviris_f151026t01p00r07_sc01
aviris_f151026t01p00r09_sc01
aviris_f151026t01p00r23_sc01
aviris_f151030t01p00r06_sc01
aviris_f151030t01p00r11_sc01
aviris_f151030t01p00r12_sc01
aviris_f151030t01p00r13_sc01
aviris_f160324t01p00r06_sc01
aviris_f160324t01p00r08_sc01
aviris_f160512t01p00r12_sc01
aviris_f160512t01p00r13_sc01
aviris_f160518t01p00r05_sc01
aviris_f160518t01p00r06_sc01
aviris_f160518t01p00r09_sc01
aviris_f160609t01p00r12_sc01
aviris_f160616t01p00r08_sc01
aviris_f160616t01p00r09_sc01
aviris_f160616t01p00r10_sc01
aviris_f160616t01p00r11_sc01
aviris_f160616t01p00r12_sc01
aviris_f160616t01p00r13_sc01
aviris_f160616t01p00r14_sc01
aviris_f160616t01p00r15_sc01
aviris_f160616t01p00r16_sc01
aviris_f160616t01p00r17_sc01
aviris_f160617t01p00r09_sc01
aviris_f160617t01p00r10_sc01
aviris_f160617t01p00r12_sc01
aviris_f160617t01p00r14_sc01
aviris_f160617t01p00r16_sc01
aviris_f160617t01p00r19_sc01
aviris_f160620t01p00r07_sc01
aviris_f160620t01p00r08_sc01
aviris_f160620t01p00r09_sc01
aviris_f160620t01p00r10_sc01
aviris_f160620t01p00r11_sc01
aviris_f160620t01p00r12_sc01
aviris_f160620t01p00r13_sc01
aviris_f160620t01p00r14_sc01
aviris_f160620t01p00r15_sc01
aviris_f160620t01p00r16_sc01
aviris_f160621t01p00r06_sc01
aviris_f160621t01p00r09_sc01
aviris_f160621t01p00r10_sc01
aviris_f160621t01p00r11_sc01
aviris_f160621t01p00r16_sc01
aviris_f160621t01p00r17_sc01
aviris_f160622t01p00r01_sc01
aviris_f160622t01p00r02_sc01
aviris_f160622t01p00r03_sc01
aviris_f160622t01p00r04_sc01
aviris_f170416t01p00r14_sc01
aviris_f170418t01p00r08_sc01
aviris_f170418t01p00r09_sc01
aviris_f170418t01p00r11_sc01
aviris_f170514t01p00r29_sc01
aviris_f170607t01p00r08_sc01
aviris_f170607t01p00r15_sc01
aviris_f170607t01p00r17_sc01
aviris_f170626t01p00r08_sc01
aviris_f170626t01p00r11_sc01
aviris_f170628t01p00r16_sc01
aviris_f170628t01p00r18_sc01
aviris_f170628t01p00r20_sc01
aviris_f170628t01p00r21_sc01
aviris_f170628t01p00r22_sc01
aviris_f170628t01p00r23_sc01
aviris_f170628t01p00r24_sc01
aviris_f170628t01p00r25_sc01
aviris_f171204t01p00r11_sc01
aviris_f171204t01p00r13_sc01
aviris_f171204t01p00r15_sc01
aviris_f171204t01p00r25_sc01
aviris_f171206t01p00r15_sc01
aviris_f171206t01p00r17_sc01
aviris_f171206t01p00r18_sc01
aviris_f171207t01p00r19_sc01
aviris_f171214t01p00r08_sc01
aviris_f171221t01p00r09_sc01
aviris_f171221t01p00r11_sc01
aviris_f171221t01p00r14_sc01
aviris_f171221t01p00r16_sc01
aviris_f171221t01p00r19_sc01
aviris_f180111t01p00r10_sc01
aviris_f180111t01p00r11_sc01
aviris_f180111t01p00r14_sc01
aviris_f180522t01p00r12_sc01
aviris_f180529t01p00r06_sc01
aviris_f180529t01p00r08_sc01
aviris_f180529t01p00r09_sc01
aviris_f180529t01p00r10_sc01
aviris_f180601t01p00r06_sc01
aviris_f180601t01p00r07_sc01
aviris_f180601t01p00r10_sc01
aviris_f180601t01p00r11_sc01
aviris_f180604t01p00r07_sc01
aviris_f180604t01p00r10_sc01
aviris_f180604t01p00r12_sc01
aviris_f180608t01p00r06_sc01
aviris_f180608t01p00r07_sc01
aviris_f180608t01p00r10_sc01
aviris_f180612t01p00r08_sc01
aviris_f180612t01p00r09_sc01
aviris_f180612t01p00r10_sc01
aviris_f180612t01p00r11_sc01
aviris_f180619t01p00r10_sc01
aviris_f180619t01p00r11_sc01
aviris_f180620t01p00r07_sc01
aviris_f180621t01p00r08_sc01
aviris_f180621t01p00r11_sc01
aviris_f180621t01p00r13_sc01
aviris_f180621t01p00r16_sc01
aviris_f180622t01p00r05_sc01
aviris_f180622t01p00r06_sc01
aviris_f180622t01p00r09_sc01
aviris_f180622t01p00r10_sc01
aviris_f180622t01p00r13_sc01
aviris_f180625t01p00r05_sc01
aviris_f180625t01p00r06_sc01
aviris_f180625t01p00r07_sc01
aviris_f180625t01p00r08_sc01
aviris_f180625t01p00r09_sc01
aviris_f180625t01p00r10_sc01
aviris_f180625t01p00r11_sc01
aviris_f180625t01p00r12_sc01
aviris_f180625t01p00r13_sc01
aviris_f180625t01p00r14_sc01
aviris_f180627t01p00r06_sc01
aviris_f180628t02p00r05_sc01
aviris_f180628t02p00r07_sc01
aviris_f180628t02p00r09_sc01
aviris_f180628t02p00r14_sc01
aviris_f180628t02p00r15_sc01
aviris_f180828t01p00r08_sc01
aviris_f180828t01p00r10_sc01
aviris_f180831t01p00r08_sc01
aviris_f180831t01p00r09_sc01
aviris_f180831t01p00r10_sc01
aviris_f180831t01p00r11_sc01
aviris_f180904t01p00r06_sc01
aviris_f180904t01p00r08_sc01
aviris_f180904t01p00r09_sc01
aviris_f180913t01p00r11_sc01
aviris_f180913t01p00r12_sc01
aviris_f180917t01p00r05_sc01
aviris_f180918t01p00r06_sc01
aviris_f190802t01p00r08_sc01
aviris_f190802t01p00r12_sc01
aviris_f190802t01p00r15_sc01
aviris_f190808t01p00r14_sc01
aviris_f190808t01p00r17_sc01
aviris_f190812t01p00r06_sc01
aviris_f190812t01p00r07_sc01
aviris_f190912t01p00r07_sc01
aviris_f190912t01p00r08_sc01
aviris_f190925t01p00r06_sc01
aviris_f190925t01p00r08_sc01
aviris_f190925t01p00r10_sc01
aviris_f190925t01p00r15_sc01
aviris_f190925t01p00r16_sc01
aviris_f191001t01p00r05_sc01
aviris_f191001t01p00r08_sc01
aviris_f191001t01p00r09_sc01
aviris_f191001t01p00r12_sc01
aviris_f191001t01p00r15_sc01
aviris_f191001t01p00r16_sc01

**Comment by jpolchlo** [comment]
That long list was bothering me.  I went back, picked only the largest 15 landfills per climate zone, and then selected only the most recent half dozen images per landfill.  This pared the number of scenes way down.  There are now a more manageable 106 scenes.  If this seems too large still, I can easily trim the number.

Here's the list:

aviris_f130410t01p00r10_sc01
aviris_f130410t01p00r11_sc01
aviris_f130410t01p00r13_sc01
aviris_f130410t01p00r14_sc01
aviris_f130410t01p00r15_sc01
aviris_f130410t01p00r16_sc01
aviris_f130410t01p00r18_sc01
aviris_f130410t01p00r19_sc01
aviris_f130412t01p00r07_sc01
aviris_f130412t01p00r08_sc01
aviris_f130412t01p00r09_sc01
aviris_f130412t01p00r11_sc01
aviris_f130412t01p00r13_sc01
aviris_f130412t01p00r14_sc01
aviris_f130419t01p00r08_sc01
aviris_f130419t01p00r09_sc01
aviris_f130419t01p00r10_sc01
aviris_f130419t01p00r12_sc01
aviris_f130419t01p00r13_sc01
aviris_f130419t01p00r14_sc01
aviris_f130419t01p00r15_sc01
aviris_f130502t01p00r07_sc01
aviris_f130502t01p00r18_sc01
aviris_f130502t01p00r23_sc01
aviris_f130503t01p00r14_sc01
aviris_f130503t01p00r15_sc01
aviris_f130503t01p00r22_sc01
aviris_f130522t01p00r07_sc01
aviris_f130522t01p00r08_sc01
aviris_f130522t01p00r09_sc01
aviris_f130522t01p00r11_sc01
aviris_f130522t01p00r12_sc01
aviris_f130522t01p00r13_sc01
aviris_f130522t01p00r14_sc01
aviris_f130522t01p00r15_sc01
aviris_f130604t01p00r11_sc01
aviris_f130606t01p00r05_sc01
aviris_f130607t01p00r05_sc01
aviris_f130607t01p00r08_sc01
aviris_f130607t01p00r09_sc01
aviris_f130607t01p00r10_sc01
aviris_f130607t01p00r11_sc01
aviris_f130607t01p00r12_sc01
aviris_f130607t01p00r13_sc01
aviris_f130607t01p00r14_sc01
aviris_f130612t01p00r06_sc01
aviris_f130612t01p00r07_sc01
aviris_f130612t01p00r14_sc01
aviris_f130626t01p00r07_sc01
aviris_f130924t01p00r07_sc01
aviris_f130924t01p00r08_sc01
aviris_f130924t01p00r09_sc01
aviris_f130924t01p00r11_sc01
aviris_f130924t01p00r12_sc01
aviris_f130924t01p00r13_sc01
aviris_f131117t01p00r05_sc01
aviris_f140331t01p00r12_sc01
aviris_f140410t01p00r13_sc01
aviris_f140414t01p00r07_sc01
aviris_f140414t01p00r08_sc01
aviris_f140414t01p00r11_sc01
aviris_f140414t01p00r12_sc01
aviris_f140414t01p00r13_sc01
aviris_f140414t01p00r14_sc01
aviris_f140418t01p00r07_sc01
aviris_f140418t01p00r09_sc01
aviris_f140418t01p00r10_sc01
aviris_f140418t01p00r11_sc01
aviris_f140423t01p00r07_sc01
aviris_f140423t01p00r08_sc01
aviris_f140507t01p00r06_sc01
aviris_f140507t01p00r07_sc01
aviris_f140507t01p00r13_sc01
aviris_f140507t01p00r15_sc01
aviris_f140528t01p00r06_sc01
aviris_f140528t01p00r07_sc01
aviris_f140528t01p00r08_sc01
aviris_f140528t01p00r10_sc01
aviris_f140602t01p00r15_sc01
aviris_f140919t01p00r14_sc01
aviris_f141027t01p00r07_sc01
aviris_f151026t01p00r09_sc01
aviris_f160518t01p00r09_sc01
aviris_f170411t01p00r09_sc01
aviris_f170416t01p00r14_sc01
aviris_f170418t01p00r09_sc01
aviris_f170418t01p00r11_sc01
aviris_f170418t01p00r12_sc01
aviris_f170514t01p00r29_sc01
aviris_f171204t01p00r25_sc01
aviris_f171214t01p00r08_sc01
aviris_f171221t01p00r09_sc01
aviris_f180529t01p00r06_sc01
aviris_f180601t01p00r06_sc01
aviris_f180604t01p00r07_sc01
aviris_f180612t01p00r08_sc01
aviris_f180612t01p00r10_sc01
aviris_f180828t01p00r10_sc01
aviris_f180831t01p00r08_sc01
aviris_f180831t01p00r09_sc01
aviris_f180904t01p00r06_sc01
aviris_f180904t01p00r08_sc01
aviris_f180917t01p00r05_sc01
aviris_f180918t01p00r06_sc01
aviris_f190808t01p00r14_sc01
aviris_f190808t01p00r17_sc01

**Comment by CloudNiner** [comment]
Looks great. We'll let you know when we're ready to ingest if we need to cut the list further.

> Franklin query for these IDs returned a feature collection with the context line `{'returned': 30, 'matched': 3741}`

That seems wrong -- the 3741 is the total number of items in the collection. I'd expect the 'matched' number to equal or be slightly less (if it couldn't find some) than the number of items you pass in the list.

Can you post or DM me the code you used to do the query?

**Comment by pomadchin** [comment]
The next thing with this list of scenes is to kick the activation step. It is captured in the follow up issue #85.

Thanks!
